name: Build project and run tests
on: [pull_request, push]
jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    if: github.repository_owner == 'TroupeLang' 
    env:
        STACK_OPTS: "--system-ghc"
        TROUPE: ${{github.workspace}}
        TERM: "xterm-color"
    steps:
      - name: install missing dependency for ghc
        # https://gitlab.haskell.org/ghc/ghc/-/issues/15444
        run: |
          sudo apt-get update
          sudo apt-get install -y libnuma-dev diffutils
      
      - uses: actions/checkout@v4
      
      # Cache Stack dependencies
      - name: Cache Stack
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            compiler/.stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('compiler/stack.yaml', 'compiler/package.yaml', 'compiler/*.cabal') }}
          restore-keys: |
            ${{ runner.os }}-stack-
      
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.8' # Exact version of ghc to use
          # cabal-version: 'latest'. Omitted, but defaults to 'latest'
          enable-stack: true
          # stack-version: 'latest'
      
      - name: compile the compiler
        run: make compiler
      
      - uses: actions/setup-node@v4
      
      - run: make npm
      - name: compile the runtime
        run: make rt
      - name: compile libs
        run: make libs
      - name: compile service
        run: make service
      - name: golden tests
        run: make ci-test-golden-no-color
